version: 2.1

executors:
  clang:
    docker:
    - image: kayess/cpp
    environment:
      CC: clang
      CXX: clang++
  clang-libcpp:
    docker:
    - image: kayess/cpp
    environment:
      CC: clang
      CXX: clang++
      CXXFLAGS: "-stdlib=libc++"
      LD_FLAGS: "-stdlib=libc++"
  clang-asan:
    docker:
    - image: kayess/cpp
    environment:
      CC: clang
      CXX: clang++
      CXXFLAGS: "-stdlib=libc++ -fsanitize=address"
      LD_FLAGS: "-stdlib=libc++ -fsanitize=address"
      ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
  gcc:
    docker:
    - image: kayess/cpp
    environment:
      CC: gcc
      CXX: g++
  gcc-pmr:
    docker:
    - image: kayess/cpp
    environment:
      CC: gcc
      CXX: g++
      FELSPAR_FORCE_PMR: YES

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout

      - run:
          name: cmake
          environment:
            CMAKE_BUILD_TYPE: << parameters.variant >>
          command: cmake -G Ninja -S . -B build.tmp/

      - run:
          name: ninja
          command: ninja -C build.tmp/
      - run:
          name: check tests
          command: ninja -C build.tmp/ felspar-check

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang, clang-libcpp, clang-asan, gcc-pmr]
              variant: [Debug, Release]
